
export default function Home() {
  return (
    <div className="bg-bg3  h-full  bg-contain bg-center ">
       <div className="flex justify-between mt-[20]">
        <section className="text-white text-[20px] font-bold h-full w-[35%] mt-[20px] ml-5"> <span className="text-[35px]">REGLAS DE USO</span> <br/>
        ESTAS SON LAS REGLAS DE USO QUE DEBES SEGUIR. POR FAVOR, PRESTA ATENCIÓN Y CÚMPLASLAS. PRIMERO, MANTÉN UN COMPORTAMIENTO RESPETUOSO EN TODO MOMENTO. SEGUNDO, NO HAGAS USO INAPROPIADO DEL CONTENIDO. TERCERO, RESPETA LOS DERECHOS DE AUTOR Y LA PROPIEDAD INTELECTUAL. CUARTO, NO DIFUNDAS INFORMACIÓN FALSA O MALICIOSA. QUINTO, NO REALICES ACTIVIDADES ILEGALES O QUE INFRINJAN LAS LEYES. SEXTO, CUIDA LA PRIVACIDAD DE LOS DEMÁS Y NO REVELES INFORMACIÓN PERSONAL. SÉPTIMO, NO PROMUEVAS DISCRIMINACIÓN, ODIO O VIOLENCIA. OCTAVO, MANTÉN LA INTEGRIDAD DE LOS SISTEMAS Y RECURSOS. NOVENO, SIGUE LAS INSTRUCCIONES DEL PERSONAL RESPONSABLE. DÉCIMO, SI TIENES ALGUNA DUDA O INQUIETUD, CONSULTA CON LOS ADMINISTRADORES. CUMPLE ESTAS REGLAS PARA UN USO ADECUADO
        </section>
        <section className="text-white text-[20px] font-bold h-full  w-[35%] mt-[20px] mr-5"><span className="text-[35px]">ADVERTENCIA</span> <br /> 
        ESTE SITIO CONTIENE INFORMACIÓN SENSIBLE Y RESTRINGIDA. EL ACCESO NO AUTORIZADO ESTÁ ESTRICTAMENTE PROHIBIDO. CUALQUIER INTENTO DE INGRESAR SIN PERMISO SERÁ CONSIDERADO UN DELITO. LA DIVULGACIÓN NO AUTORIZADA DE ESTE CONTENIDO PUEDE RESULTAR EN ACCIONES LEGALES. POR FAVOR, ABSTÉNGASE DE INTENTAR ACCEDER A ÁREAS RESTRINGIDAS O REALIZAR ACTIVIDADES MALICIOSAS. TODA LA INFORMACIÓN AQUÍ PRESENTADA ES CONFIDENCIAL Y DE USO EXCLUSIVO PARA PERSONAL AUTORIZADO. SE RUEGA REPORTAR CUALQUIER ACTIVIDAD SOSPECHOSA O VIOLACIÓN DE SEGURIDAD. ESTE SISTEMA ES MONITOREADO CONSTANTEMENTE. AL CONTINUAR, ACEPTA LOS TÉRMINOS Y CONDICIONES DE USO. EL INCUMPLIMIENTO DE ESTAS ADVERTENCIAS PUEDE ACARREAR CONSECUENCIAS LEGALES GRAVES.</section>
       </div>
    </div>
  )
}
